FROM python:3.10-alpine
ARG HF_TOKEN
ENV HF_TOKEN=${HF_TOKEN}
WORKDIR /code
COPY . .
RUN pip install --no-cache-dir -r requirements.txt
EXPOSE 8000
CMD [ "uvicorn", "models:app", "--host", "0.0.0.0", "--reload" ]