version: "3.9"

services:
  redis-database:
    image: "redis:alpine"
    restart: always
    ports:
      - '6379:6379'
    networks:
      - my-network 

  web-app:
    build:
      context: .
      dockerfile: Dockerfile.fastapi
    container_name: fast-api-app
    ports:
      - "8000:8000"
    volumes:
      - .:/code 
    depends_on:
      - redis-database
    networks:
      - my-network
    
  gui-app:
    build:
      context: .
      dockerfile: Dockerfile.gui
    container_name: streamgui-app
    ports:
      - "9000:8501"
    volumes:
      - .:/code
    networks:
      - my-network

networks:
  my-network:
