name: Run FastAPI Test

on:
  push:
    branches: [main]

jobs:
  test-my-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

    

      - name: Build FastAPI Docker image
        run: docker build -f Dockerfile.fastapi -t fastapi-app .

      - name: Run FastAPI container
        run: |
          docker run -d -p 8000:8000 --name fastapi-container fastapi-app
      
      - name: Wait for FatAPI to be ready.
        run: |
          for i in {1..30}; do
            echo "Waiting for FastAPI to be ready... attempt $i"
            if curl -s http://localhost:8000/docs > /dev/null; then
              echo "FastAPI is up!"
              break
            fi
            sleep 1
          done


      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest testAPI.py

      - name: Stop container
        if: always()
        run: docker stop fastapi-container && docker rm fastapi-container
