name: Run FastAPI Test

on:
  push:
    branches: [main]

jobs:
  test-my-app:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

    

      - name: Build FastAPI Docker image
        run: docker build -f Dockerfile.fastapi -t fastapi-app .

      - name: Run FastAPI container
        run: |
          docker run -d -p 8000:8000 --name fastapi-container fastapi-app
          sleep 5  # wait a bit to let it start

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run tests
        run: pytest tests/

      - name: Stop container
        if: always()
        run: docker stop fastapi-container && docker rm fastapi-container
