name: Run FastAPI Test

on:
  push:
    branches: [main]

jobs:
  test:
    runs-on: ubuntu-latest

    services:
      fastapi:
        build:
          context: .
          dockerfile: Dockerfile.fastapi
        ports:
          - 8000:8000
        options: >-
          --health-cmd="curl --fail http://localhost:8000/docs || exit 1"
          --health-interval=5s
          --health-timeout=3s
          --health-retries=5

    steps:
      - name: Checkout the code
        uses: actions/checkout@v3

      - name: Set up Python
        uses: actions/setup-python@v4
        with:
          python-version: 3.10

      - name: Install dependencies
        run: |
          pip install -r requirements.txt
          pip install pytest

      - name: Run pytest
        run: pytest tests/
